name: Rust

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - 'Cargo.toml'
      - 'Cargo-lock.toml'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --release
    - name: Move the binary to root
      run: mv -f target/release/summarizer .
    - name: Commit the binary to the repo
      run: |
          git config user.name 'look at him go'
          git add summarizer
          git commit -m "Build binary on $(date -Iminutes)"
          git push
