name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --release
    - run: ls -laR
    - name: Move the binary to root
      run: mv -f target/release/summarizer .
    - run: ls -laR
    - name: Commit the binary to the repo
      run: |
        if ! git diff-index --quiet HEAD --; then
          git config user.name 'look at him go'
          git add summarizer
          git commit -m "Build binary on $(date -Iminutes)"
          git push
        fi
    
