name: Cron

on:
  workflow_dispatch:
  schedule:
   - cron: '0 */12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - env:
          DAYS: ${{ secrets.DAYS }}
          GH_DATA_PATH: ${{ secrets.GH_DATA_PATH }}
          GH_GIST_ID: ${{ GH_GIST_ID }}
          GH_PAT: ${{ GH_PAT }}
        run: ./summarizer
